// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc-core.proto

package com.nobodyhub.payroll.core.service.proto;

public final class PayrollCoreProtocol {
  private PayrollCoreProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:payroll.core.service.proto.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the id of task to be triggerred
     * </pre>
     *
     * <code>string taskId = 1;</code>
     */
    java.lang.String getTaskId();
    /**
     * <pre>
     * the id of task to be triggerred
     * </pre>
     *
     * <code>string taskId = 1;</code>
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <pre>
     * the identifier of the &lt;code&gt;values&lt;/code&gt;
     * </pre>
     *
     * <code>string dataId = 2;</code>
     */
    java.lang.String getDataId();
    /**
     * <pre>
     * the identifier of the &lt;code&gt;values&lt;/code&gt;
     * </pre>
     *
     * <code>string dataId = 2;</code>
     */
    com.google.protobuf.ByteString
        getDataIdBytes();

    /**
     * <pre>
     * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 3;</code>
     */
    int getValuesCount();
    /**
     * <pre>
     * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 3;</code>
     */
    boolean containsValues(
        java.lang.String key);
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getValues();
    /**
     * <pre>
     * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getValuesMap();
    /**
     * <pre>
     * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 3;</code>
     */

    java.lang.String getValuesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 3;</code>
     */

    java.lang.String getValuesOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * Request sent for calculation, each per employee
   * </pre>
   *
   * Protobuf type {@code payroll.core.service.proto.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:payroll.core.service.proto.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
      taskId_ = "";
      dataId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              taskId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              dataId_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                values_ = com.google.protobuf.MapField.newMapField(
                    ValuesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              values__ = input.readMessage(
                  ValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              values_.getMutableMap().put(
                  values__.getKey(), values__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.internal_static_payroll_core_service_proto_Request_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.internal_static_payroll_core_service_proto_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request.class, com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request.Builder.class);
    }

    private int bitField0_;
    public static final int TASKID_FIELD_NUMBER = 1;
    private volatile java.lang.Object taskId_;
    /**
     * <pre>
     * the id of task to be triggerred
     * </pre>
     *
     * <code>string taskId = 1;</code>
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the id of task to be triggerred
     * </pre>
     *
     * <code>string taskId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATAID_FIELD_NUMBER = 2;
    private volatile java.lang.Object dataId_;
    /**
     * <pre>
     * the identifier of the &lt;code&gt;values&lt;/code&gt;
     * </pre>
     *
     * <code>string dataId = 2;</code>
     */
    public java.lang.String getDataId() {
      java.lang.Object ref = dataId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the identifier of the &lt;code&gt;values&lt;/code&gt;
     * </pre>
     *
     * <code>string dataId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataIdBytes() {
      java.lang.Object ref = dataId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUES_FIELD_NUMBER = 3;
    private static final class ValuesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.internal_static_payroll_core_service_proto_Request_ValuesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> values_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetValues() {
      if (values_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValuesDefaultEntryHolder.defaultEntry);
      }
      return values_;
    }

    public int getValuesCount() {
      return internalGetValues().getMap().size();
    }
    /**
     * <pre>
     * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 3;</code>
     */

    public boolean containsValues(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetValues().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getValues() {
      return getValuesMap();
    }
    /**
     * <pre>
     * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getValuesMap() {
      return internalGetValues().getMap();
    }
    /**
     * <pre>
     * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 3;</code>
     */

    public java.lang.String getValuesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetValues().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 3;</code>
     */

    public java.lang.String getValuesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetValues().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTaskIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskId_);
      }
      if (!getDataIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dataId_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetValues(),
          ValuesDefaultEntryHolder.defaultEntry,
          3);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTaskIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskId_);
      }
      if (!getDataIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dataId_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetValues().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        values__ = ValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, values__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request)) {
        return super.equals(obj);
      }
      com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request other = (com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request) obj;

      boolean result = true;
      result = result && getTaskId()
          .equals(other.getTaskId());
      result = result && getDataId()
          .equals(other.getDataId());
      result = result && internalGetValues().equals(
          other.internalGetValues());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId().hashCode();
      hash = (37 * hash) + DATAID_FIELD_NUMBER;
      hash = (53 * hash) + getDataId().hashCode();
      if (!internalGetValues().getMap().isEmpty()) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetValues().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Request sent for calculation, each per employee
     * </pre>
     *
     * Protobuf type {@code payroll.core.service.proto.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:payroll.core.service.proto.Request)
        com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.internal_static_payroll_core_service_proto_Request_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.internal_static_payroll_core_service_proto_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request.class, com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request.Builder.class);
      }

      // Construct using com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        taskId_ = "";

        dataId_ = "";

        internalGetMutableValues().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.internal_static_payroll_core_service_proto_Request_descriptor;
      }

      public com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request getDefaultInstanceForType() {
        return com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request.getDefaultInstance();
      }

      public com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request build() {
        com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request buildPartial() {
        com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request result = new com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.taskId_ = taskId_;
        result.dataId_ = dataId_;
        result.values_ = internalGetValues();
        result.values_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request) {
          return mergeFrom((com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request other) {
        if (other == com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request.getDefaultInstance()) return this;
        if (!other.getTaskId().isEmpty()) {
          taskId_ = other.taskId_;
          onChanged();
        }
        if (!other.getDataId().isEmpty()) {
          dataId_ = other.dataId_;
          onChanged();
        }
        internalGetMutableValues().mergeFrom(
            other.internalGetValues());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object taskId_ = "";
      /**
       * <pre>
       * the id of task to be triggerred
       * </pre>
       *
       * <code>string taskId = 1;</code>
       */
      public java.lang.String getTaskId() {
        java.lang.Object ref = taskId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the id of task to be triggerred
       * </pre>
       *
       * <code>string taskId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        java.lang.Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the id of task to be triggerred
       * </pre>
       *
       * <code>string taskId = 1;</code>
       */
      public Builder setTaskId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the id of task to be triggerred
       * </pre>
       *
       * <code>string taskId = 1;</code>
       */
      public Builder clearTaskId() {
        
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the id of task to be triggerred
       * </pre>
       *
       * <code>string taskId = 1;</code>
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataId_ = "";
      /**
       * <pre>
       * the identifier of the &lt;code&gt;values&lt;/code&gt;
       * </pre>
       *
       * <code>string dataId = 2;</code>
       */
      public java.lang.String getDataId() {
        java.lang.Object ref = dataId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the identifier of the &lt;code&gt;values&lt;/code&gt;
       * </pre>
       *
       * <code>string dataId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDataIdBytes() {
        java.lang.Object ref = dataId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the identifier of the &lt;code&gt;values&lt;/code&gt;
       * </pre>
       *
       * <code>string dataId = 2;</code>
       */
      public Builder setDataId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the identifier of the &lt;code&gt;values&lt;/code&gt;
       * </pre>
       *
       * <code>string dataId = 2;</code>
       */
      public Builder clearDataId() {
        
        dataId_ = getDefaultInstance().getDataId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the identifier of the &lt;code&gt;values&lt;/code&gt;
       * </pre>
       *
       * <code>string dataId = 2;</code>
       */
      public Builder setDataIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> values_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetValues() {
        if (values_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        return values_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableValues() {
        onChanged();;
        if (values_ == null) {
          values_ = com.google.protobuf.MapField.newMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        if (!values_.isMutable()) {
          values_ = values_.copy();
        }
        return values_;
      }

      public int getValuesCount() {
        return internalGetValues().getMap().size();
      }
      /**
       * <pre>
       * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
       * </pre>
       *
       * <code>map&lt;string, string&gt; values = 3;</code>
       */

      public boolean containsValues(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetValues().getMap().containsKey(key);
      }
      /**
       * Use {@link #getValuesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getValues() {
        return getValuesMap();
      }
      /**
       * <pre>
       * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
       * </pre>
       *
       * <code>map&lt;string, string&gt; values = 3;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getValuesMap() {
        return internalGetValues().getMap();
      }
      /**
       * <pre>
       * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
       * </pre>
       *
       * <code>map&lt;string, string&gt; values = 3;</code>
       */

      public java.lang.String getValuesOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetValues().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
       * </pre>
       *
       * <code>map&lt;string, string&gt; values = 3;</code>
       */

      public java.lang.String getValuesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetValues().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearValues() {
        internalGetMutableValues().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
       * </pre>
       *
       * <code>map&lt;string, string&gt; values = 3;</code>
       */

      public Builder removeValues(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableValues().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableValues() {
        return internalGetMutableValues().getMutableMap();
      }
      /**
       * <pre>
       * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
       * </pre>
       *
       * <code>map&lt;string, string&gt; values = 3;</code>
       */
      public Builder putValues(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableValues().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * the data identified by the &lt;code&gt;dataId&lt;/code&gt;
       * </pre>
       *
       * <code>map&lt;string, string&gt; values = 3;</code>
       */

      public Builder putAllValues(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableValues().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:payroll.core.service.proto.Request)
    }

    // @@protoc_insertion_point(class_scope:payroll.core.service.proto.Request)
    private static final com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request();
    }

    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    public com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:payroll.core.service.proto.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the status code
     * </pre>
     *
     * <code>string statusCode = 1;</code>
     */
    java.lang.String getStatusCode();
    /**
     * <pre>
     * the status code
     * </pre>
     *
     * <code>string statusCode = 1;</code>
     */
    com.google.protobuf.ByteString
        getStatusCodeBytes();

    /**
     * <pre>
     * the message, if any, to describe the status code
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * the message, if any, to describe the status code
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     * the identifier of the &lt;code&gt;values&lt;/code&gt;
     * </pre>
     *
     * <code>string dataId = 3;</code>
     */
    java.lang.String getDataId();
    /**
     * <pre>
     * the identifier of the &lt;code&gt;values&lt;/code&gt;
     * </pre>
     *
     * <code>string dataId = 3;</code>
     */
    com.google.protobuf.ByteString
        getDataIdBytes();

    /**
     * <pre>
     * the result values
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 4;</code>
     */
    int getValuesCount();
    /**
     * <pre>
     * the result values
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 4;</code>
     */
    boolean containsValues(
        java.lang.String key);
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getValues();
    /**
     * <pre>
     * the result values
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getValuesMap();
    /**
     * <pre>
     * the result values
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 4;</code>
     */

    java.lang.String getValuesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <pre>
     * the result values
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 4;</code>
     */

    java.lang.String getValuesOrThrow(
        java.lang.String key);
  }
  /**
   * <pre>
   * Response results from calculation, each per employee
   * </pre>
   *
   * Protobuf type {@code payroll.core.service.proto.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:payroll.core.service.proto.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      statusCode_ = "";
      message_ = "";
      dataId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              statusCode_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              dataId_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                values_ = com.google.protobuf.MapField.newMapField(
                    ValuesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              values__ = input.readMessage(
                  ValuesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              values_.getMutableMap().put(
                  values__.getKey(), values__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.internal_static_payroll_core_service_proto_Response_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetValues();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.internal_static_payroll_core_service_proto_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response.class, com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response.Builder.class);
    }

    private int bitField0_;
    public static final int STATUSCODE_FIELD_NUMBER = 1;
    private volatile java.lang.Object statusCode_;
    /**
     * <pre>
     * the status code
     * </pre>
     *
     * <code>string statusCode = 1;</code>
     */
    public java.lang.String getStatusCode() {
      java.lang.Object ref = statusCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statusCode_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the status code
     * </pre>
     *
     * <code>string statusCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStatusCodeBytes() {
      java.lang.Object ref = statusCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statusCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * the message, if any, to describe the status code
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the message, if any, to describe the status code
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATAID_FIELD_NUMBER = 3;
    private volatile java.lang.Object dataId_;
    /**
     * <pre>
     * the identifier of the &lt;code&gt;values&lt;/code&gt;
     * </pre>
     *
     * <code>string dataId = 3;</code>
     */
    public java.lang.String getDataId() {
      java.lang.Object ref = dataId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * the identifier of the &lt;code&gt;values&lt;/code&gt;
     * </pre>
     *
     * <code>string dataId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataIdBytes() {
      java.lang.Object ref = dataId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUES_FIELD_NUMBER = 4;
    private static final class ValuesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.internal_static_payroll_core_service_proto_Response_ValuesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> values_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetValues() {
      if (values_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ValuesDefaultEntryHolder.defaultEntry);
      }
      return values_;
    }

    public int getValuesCount() {
      return internalGetValues().getMap().size();
    }
    /**
     * <pre>
     * the result values
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 4;</code>
     */

    public boolean containsValues(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetValues().getMap().containsKey(key);
    }
    /**
     * Use {@link #getValuesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getValues() {
      return getValuesMap();
    }
    /**
     * <pre>
     * the result values
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 4;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getValuesMap() {
      return internalGetValues().getMap();
    }
    /**
     * <pre>
     * the result values
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 4;</code>
     */

    public java.lang.String getValuesOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetValues().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * the result values
     * </pre>
     *
     * <code>map&lt;string, string&gt; values = 4;</code>
     */

    public java.lang.String getValuesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetValues().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStatusCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, statusCode_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
      }
      if (!getDataIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dataId_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetValues(),
          ValuesDefaultEntryHolder.defaultEntry,
          4);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStatusCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, statusCode_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
      }
      if (!getDataIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dataId_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetValues().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        values__ = ValuesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, values__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response)) {
        return super.equals(obj);
      }
      com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response other = (com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response) obj;

      boolean result = true;
      result = result && getStatusCode()
          .equals(other.getStatusCode());
      result = result && getMessage()
          .equals(other.getMessage());
      result = result && getDataId()
          .equals(other.getDataId());
      result = result && internalGetValues().equals(
          other.internalGetValues());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUSCODE_FIELD_NUMBER;
      hash = (53 * hash) + getStatusCode().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + DATAID_FIELD_NUMBER;
      hash = (53 * hash) + getDataId().hashCode();
      if (!internalGetValues().getMap().isEmpty()) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetValues().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Response results from calculation, each per employee
     * </pre>
     *
     * Protobuf type {@code payroll.core.service.proto.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:payroll.core.service.proto.Response)
        com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.internal_static_payroll_core_service_proto_Response_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableValues();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.internal_static_payroll_core_service_proto_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response.class, com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response.Builder.class);
      }

      // Construct using com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        statusCode_ = "";

        message_ = "";

        dataId_ = "";

        internalGetMutableValues().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.internal_static_payroll_core_service_proto_Response_descriptor;
      }

      public com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response getDefaultInstanceForType() {
        return com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response.getDefaultInstance();
      }

      public com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response build() {
        com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response buildPartial() {
        com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response result = new com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.statusCode_ = statusCode_;
        result.message_ = message_;
        result.dataId_ = dataId_;
        result.values_ = internalGetValues();
        result.values_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response) {
          return mergeFrom((com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response other) {
        if (other == com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response.getDefaultInstance()) return this;
        if (!other.getStatusCode().isEmpty()) {
          statusCode_ = other.statusCode_;
          onChanged();
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.getDataId().isEmpty()) {
          dataId_ = other.dataId_;
          onChanged();
        }
        internalGetMutableValues().mergeFrom(
            other.internalGetValues());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object statusCode_ = "";
      /**
       * <pre>
       * the status code
       * </pre>
       *
       * <code>string statusCode = 1;</code>
       */
      public java.lang.String getStatusCode() {
        java.lang.Object ref = statusCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          statusCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the status code
       * </pre>
       *
       * <code>string statusCode = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStatusCodeBytes() {
        java.lang.Object ref = statusCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          statusCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the status code
       * </pre>
       *
       * <code>string statusCode = 1;</code>
       */
      public Builder setStatusCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        statusCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the status code
       * </pre>
       *
       * <code>string statusCode = 1;</code>
       */
      public Builder clearStatusCode() {
        
        statusCode_ = getDefaultInstance().getStatusCode();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the status code
       * </pre>
       *
       * <code>string statusCode = 1;</code>
       */
      public Builder setStatusCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        statusCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * the message, if any, to describe the status code
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the message, if any, to describe the status code
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the message, if any, to describe the status code
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the message, if any, to describe the status code
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the message, if any, to describe the status code
       * </pre>
       *
       * <code>string message = 2;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dataId_ = "";
      /**
       * <pre>
       * the identifier of the &lt;code&gt;values&lt;/code&gt;
       * </pre>
       *
       * <code>string dataId = 3;</code>
       */
      public java.lang.String getDataId() {
        java.lang.Object ref = dataId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * the identifier of the &lt;code&gt;values&lt;/code&gt;
       * </pre>
       *
       * <code>string dataId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDataIdBytes() {
        java.lang.Object ref = dataId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * the identifier of the &lt;code&gt;values&lt;/code&gt;
       * </pre>
       *
       * <code>string dataId = 3;</code>
       */
      public Builder setDataId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dataId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the identifier of the &lt;code&gt;values&lt;/code&gt;
       * </pre>
       *
       * <code>string dataId = 3;</code>
       */
      public Builder clearDataId() {
        
        dataId_ = getDefaultInstance().getDataId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the identifier of the &lt;code&gt;values&lt;/code&gt;
       * </pre>
       *
       * <code>string dataId = 3;</code>
       */
      public Builder setDataIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dataId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> values_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetValues() {
        if (values_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        return values_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableValues() {
        onChanged();;
        if (values_ == null) {
          values_ = com.google.protobuf.MapField.newMapField(
              ValuesDefaultEntryHolder.defaultEntry);
        }
        if (!values_.isMutable()) {
          values_ = values_.copy();
        }
        return values_;
      }

      public int getValuesCount() {
        return internalGetValues().getMap().size();
      }
      /**
       * <pre>
       * the result values
       * </pre>
       *
       * <code>map&lt;string, string&gt; values = 4;</code>
       */

      public boolean containsValues(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetValues().getMap().containsKey(key);
      }
      /**
       * Use {@link #getValuesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getValues() {
        return getValuesMap();
      }
      /**
       * <pre>
       * the result values
       * </pre>
       *
       * <code>map&lt;string, string&gt; values = 4;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getValuesMap() {
        return internalGetValues().getMap();
      }
      /**
       * <pre>
       * the result values
       * </pre>
       *
       * <code>map&lt;string, string&gt; values = 4;</code>
       */

      public java.lang.String getValuesOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetValues().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * the result values
       * </pre>
       *
       * <code>map&lt;string, string&gt; values = 4;</code>
       */

      public java.lang.String getValuesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetValues().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearValues() {
        internalGetMutableValues().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * the result values
       * </pre>
       *
       * <code>map&lt;string, string&gt; values = 4;</code>
       */

      public Builder removeValues(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableValues().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableValues() {
        return internalGetMutableValues().getMutableMap();
      }
      /**
       * <pre>
       * the result values
       * </pre>
       *
       * <code>map&lt;string, string&gt; values = 4;</code>
       */
      public Builder putValues(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableValues().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * the result values
       * </pre>
       *
       * <code>map&lt;string, string&gt; values = 4;</code>
       */

      public Builder putAllValues(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableValues().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:payroll.core.service.proto.Response)
    }

    // @@protoc_insertion_point(class_scope:payroll.core.service.proto.Response)
    private static final com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response();
    }

    public static com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public com.nobodyhub.payroll.core.service.proto.PayrollCoreProtocol.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payroll_core_service_proto_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payroll_core_service_proto_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payroll_core_service_proto_Request_ValuesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payroll_core_service_proto_Request_ValuesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payroll_core_service_proto_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payroll_core_service_proto_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_payroll_core_service_proto_Response_ValuesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_payroll_core_service_proto_Response_ValuesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017calc-core.proto\022\032payroll.core.service." +
      "proto\"\231\001\n\007Request\022\016\n\006taskId\030\001 \001(\t\022\016\n\006dat" +
      "aId\030\002 \001(\t\022?\n\006values\030\003 \003(\0132/.payroll.core" +
      ".service.proto.Request.ValuesEntry\032-\n\013Va" +
      "luesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028" +
      "\001\"\260\001\n\010Response\022\022\n\nstatusCode\030\001 \001(\t\022\017\n\007me" +
      "ssage\030\002 \001(\t\022\016\n\006dataId\030\003 \001(\t\022@\n\006values\030\004 " +
      "\003(\01320.payroll.core.service.proto.Respons" +
      "e.ValuesEntry\032-\n\013ValuesEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\t:\0028\0012m\n\022PayrollCoreServi" +
      "ce\022W\n\006doCalc\022#.payroll.core.service.prot" +
      "o.Request\032$.payroll.core.service.proto.R" +
      "esponse(\0010\001B?\n(com.nobodyhub.payroll.cor" +
      "e.service.protoB\023PayrollCoreProtocolb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_payroll_core_service_proto_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_payroll_core_service_proto_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payroll_core_service_proto_Request_descriptor,
        new java.lang.String[] { "TaskId", "DataId", "Values", });
    internal_static_payroll_core_service_proto_Request_ValuesEntry_descriptor =
      internal_static_payroll_core_service_proto_Request_descriptor.getNestedTypes().get(0);
    internal_static_payroll_core_service_proto_Request_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payroll_core_service_proto_Request_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_payroll_core_service_proto_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_payroll_core_service_proto_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payroll_core_service_proto_Response_descriptor,
        new java.lang.String[] { "StatusCode", "Message", "DataId", "Values", });
    internal_static_payroll_core_service_proto_Response_ValuesEntry_descriptor =
      internal_static_payroll_core_service_proto_Response_descriptor.getNestedTypes().get(0);
    internal_static_payroll_core_service_proto_Response_ValuesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_payroll_core_service_proto_Response_ValuesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
